name: video_watermark
description: A pure Dart/WASM flutter plugin for applying watermarks to videos across multiple platforms.
version: 0.0.1
homepage: https://github.com/Widle-Studio/Video-Watermark-Flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.0.2
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.29.0

flutter:
  plugin:
    platforms:
      android:
        package: com.widle.video_watermark
        pluginClass: VideoWatermarkPlugin
      ios:
        pluginClass: VideoWatermarkPlugin
      linux:
        pluginClass: VideoWatermarkPlugin
      macos:
        pluginClass: VideoWatermarkPlugin
      windows:
        pluginClass: VideoWatermarkPluginCApi
      web:
        pluginClass: VideoWatermarkWeb
        fileName: video_watermark_web.dart
